group: bluezone
language: go
go:
  - 1.9.2
addons:
  ssh_known_hosts: bluemix-cli-build.mybluemix.net
env:
  global:
    - REPO_SERVER=bluemix-cli-build.mybluemix.net
    - REPO_BASE=/home/builder/builds
    - REPO_USER=builder
install: true
before_script:
  - sudo apt-get install lftp
script:
  - go vet $(go list ./... | grep -v "vendor")
  - go test .
  - bin/build-all.sh
deploy:
- provider: script
    script: bin/deploy.sh qa
    skip_cleanup: true
    on:
      branch: deploy_qa
- provider: script
    script: bin/deploy.sh prod
    skip_cleanup: true
    on:
      branch: deploy_prod