group: bluezone
language: go
dist: trusty
go:
  - 1.9.2
node_js: 6
addons:
  ssh_known_hosts: bluemix-cli-build.mybluemix.net
env:
  global:
    - REPO_SERVER=bluemix-cli-build.mybluemix.net
    - REPO_BASE=/home/builder/builds
    - REPO_USER=builder
    - PLUGIN_VERSION=1.6.1
install: true
before_script:
  - node -v
  - sudo apt-get install lftp
  - go get
script:
  - go vet $(go list ./... | grep -v "vendor")
  - bin/build-all.sh

deploy:
  - provider: script
      script: bin/deploy.sh https://s3-api.us-geo.objectstorage.softlayer.net/shelldist/dev/dist/ ${PLUGIN_VERSION}
      skip_cleanup: true
      on:
        branch: master
  - provider: script
      script: bin/deploy.sh https://s3-api.us-geo.objectstorage.softlayer.net/shelldist/qa/dist/ ${PLUGIN_VERSION}
      skip_cleanup: true
      on:
        branch: deploy_qa
  - provider: script
      script: bin/deploy.sh https://s3-api.us-geo.objectstorage.softlayer.net/shelldist/prod/dist/ ${PLUGIN_VERSION}
      skip_cleanup: true
      on:
        branch: deploy_prod