group: bluezone
language: go
go:
  - 1.9.2
addons:
  ssh_known_hosts: bluemix-cli-build.mybluemix.net
env:
  global:
    - REPO_SERVER=bluemix-cli-build.mybluemix.net
    - REPO_BASE=/home/builder/builds
    - REPO_USER=builder
install: true
before_script:
  - node -v
  - sudo apt-get install lftp
  - go get -u github.com/kardianos/govendor
  - govendor sync
script:
  - go vet $(go list ./... | grep -v "vendor")
  - go test .
  - bin/build-all.sh
