language: go
go:
  - 1.12

os:
  - linux
#  - osx
  - windows

install:
  - # skip

before_script:
  - go get
  - go get "github.com/stretchr/testify/suite"

script:
  - go vet $(go list ./... | grep -v "vendor")
  - go test ./...
  - go build

deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    repo: kui-shell/kask
    branch: master
    tags: true
    condition: $TRAVIS_OS_NAME = linux
