group: bluezone
language: go
dist: trusty
go:
  - 1.9.2
node_js: 6
addons:
  ssh_known_hosts: bluemix-cli-build.mybluemix.net
env:
  global:
    - REPO_SERVER=bluemix-cli-build.mybluemix.net
    - REPO_BASE=/home/builder/builds
    - REPO_USER=builder
install: true
before_script:
  - node -v
  - sudo apt-get install lftp
  - go get
script:
  - go vet $(go list ./... | grep -v "vendor")
  - bin/build-all.sh
  - go test .
  - node bin/generate-plugin-json.js "https://s3-api.us-geo.objectstorage.softlayer.net/shelldist/dist/" "1.6.1"
